### ISSUE TITLE
Dependency problem: Failed to resolve: com.github.vikramezhil:DroidSpeech2.0:1.2

### ISSUE THREAD

**Issue by espertus** [vikramezhil/DroidSpeech2.0#7]
Following your instructions, I added the following repository to my project-level `build.gradle` file:
```groovy
maven { url "https://jitpack.io" }
```

I added this dependency to my module's `build.gradle` file, getting the version number from the [release page](https://github.com/vikramezhil/DroidSpeech2.0/releases):
```
implementation 'com.github.vikramezhil:DroidSpeech2.0:1.2'
```

When I build in Android Studio, I get this error message:
```
ERROR: Failed to resolve: com.github.vikramezhil:DroidSpeech2.0:1.2
Show in Project Structure dialog
Affected Modules: app
```

See [changes](https://github.com/espertus/firefox-voice/commit/398278a3f3e0c705daa5b6edd79b5fcab81f7d0f).

Thank you. I look forward to trying your library.

**Comment by vikramezhil** [comment]
@espertus please add **v** before the version number.

It should be `implementation 'com.github.vikramezhil:DroidSpeech2.0:v1.2'`. I have updated README as well to avoid this confusion.

**Comment by martruchafr** [comment]
Hi

Like espertus, I have followed the instructions and added the maven repository in my project's gradle file, and the following dependency in my app's gradle file:
 
**implementation 'com.github.vikramezhil: DroidSpeech2.0: v1.2'** 

![image](https://user-images.githubusercontent.com/21036358/80919568-faae5400-8d6a-11ea-875a-d17a085f0f90.png)


with the "v" as you mention, but keep throwing the same error:

_ERROR: Failed to resolve: com.github.vikramezhil: DroidSpeech2.0: v1.2
Show in Project Structure dialog
Affected Modules: app_

Could you help me?
Thank you

**Comment by martruchafr** [comment]
Fixed, I had the maven repository in wrong place

thank
