### ISSUE TITLE
How to replace the old droidspeech in my app

### ISSUE THREAD

**Issue by kmg454** [vikramezhil/DroidSpeech2.0#9]
Long time ago we buid an app using Droidspeech, now we see this new version using Kotlin. Since we are not familiar with Kotlin how do we replace the old code?

**Comment by vikramezhil** [comment]
@kmg454 This library is compatible with android java code as long as your project has migrated to android X as recommended by google.

Please refer to this java [example](https://github.com/vikramezhil/DroidSpeech2.0/blob/master/DroidKotSpeech/app/src/main/java/github/com/vikramezhil/droidkotspeechexample/MainJavaActivity.java).

**Comment by kmg454** [comment]
Hi.
I can't migrate to Android X.
You need to have compileSdk set to at least 28 in your module build.gradle to migrate to AndroidX
Our robot has it's own SDK and can't work with compileSDK 28 Max is 23
